config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, only: [:index , :show]
  scope "(:locale)", locale: /fr|en/ do
    get 'birthday', to: "pages#birthday", as: "birthday"
    get 'selection', to: "pages#selection", as: "selection"

    root to: "users#index", constraints: lambda { |r| r.env["warden"].authenticate? }
    root to: 'pages#home'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :channels, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :subscriptions, only: [:create, :destroy]
    resources :messages, only: [:create, :destroy]
  end

  get 'first-connection', to: "channels#first_connection"
  delete 'delete-selected-user/:id', to: "channels#delete_selected_user", as: "delete_selected_user"

  mount ActionCable.server => '/cable'
  mount Attachinary::Engine => "/attachinary"

  patch 'picture/:id', to: "users#picture", as: "picture"
  put 'picture/:id', to: "users#picture"

end

app/views/shared/_channel-list.html.erb
<div id="channel-list">
  <!-- <p class="btn-create"><%= link_to "Create a new channel", new_channel_path %></p> -->

  <!-- <h1><%= @channel.default_name(current_user) %></h1> -->
  <h1>Your Twweams</h1>
  <!-- <% if @channel.one_to_one? || @admin %>
    <%= link_to "edit", edit_channel_path(@channel) %>
  <% end %> -->

  <ul class="channels-users">
    <% @subscriptions.each do |subscription| %>
      <li><%= link_to subscription.user.alias, subscription.user %></li>
    <% end %>
  </ul>

  <!-- <h2> channel list </h2> -->

  <!-- <ul>
    <% current_user.channels.each do |channel| %>
      <li>
        <% if current_user.messages.last == nil %>
          <% current_user.messages.last == 0 %>
        <% end %>
        <div <%= unread_channel_class(current_user, channel, @channel)%> >
          <%= link_to channel.default_name(current_user), channel %>
        </div>
      </li>
    <% end %>
  </ul> -->
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_map.html.erb
<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' }, provider: {scrollwheel: false} }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);



        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });

  <% end %>
<% end %>

app/views/shared/_messages-box.html.erb
<div class="col-md-10" id="message-box">
  <ul id="messages-table">
    <% @channel.messages.each_with_index do |message, index| %>
      <% if current_user.birthday == message.user.birthday %>
        <% if index == @new_messages_limit %>
          New message <hr>
        <% end %>
        <li id="message-container">
          <div id="message-infos">
            <h3><%= message.user.alias %></h3>
            <p> | <%= message.updated_at.strftime("%d/%m/%y à %Hh%M")%></p>
          </div>
          <div class="content">
            <%= ((message.content[0..6] == "http://") || (message.content[0..7] == "https://")) ? ("<a href='"+message.content+"'> See picture website </a>").html_safe : message.content %>
          </div>
          <div class="iframe">
            <%= @iframely.get_oembed_json(message.first_url)["html"].html_safe if @iframely.get_oembed_json(message.first_url)["html"]  %>
          </div>
        </li>
        <div id="delete-btn">
          <% if current_user?(message.user) %>
              <%= link_to "delete", [@channel, message], method: :delete, data: {confirm: "Are you sure! Do you want delete this post"}  %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </ul>
  <%= simple_form_for [@channel, @message], remote: true do |f| %>
    <%= f.input :content, label: false, placeholder: 'Échangez, découvrez et proposez une rencontre...', id: "chat-text" %>
    <%= f.button :submit, 'Send', id:"submit-btn" %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo-01.png" %>
  <% end %>
  <% if user_signed_in? && controller_name == 'users' && action_name == 'index' %>
    <!-- <div id="form-navbar">
      <%= simple_form_for :selection, url: selection_path, method: :get do |f| %>
        <div id="date-select">
          <%= f.input :birthdate, as: :date, start_year: Date.today.year - 110, end_year: Date.today.year, label: false, selected: @birthday %>
        </div>
        <%= render 'range' %>
        <div id="gender-box">
          <%= f.input :male, as: :boolean, class: "margin-zero" %>
          <%= f.input :female, as: :boolean, class: "margin-zero" %>
        </div>
        <h1 id="find-btn"><%= f.button :submit, 'FIND' %></h1>
      <% end %>
    </div> -->
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
      <!-- Notification -->
      <%= link_to channel_path(Channel.first), class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <%= image_tag 'elements/Courrier-01.png', alt: 'menu-item', class: "courrier" %>
          <div class="hidden">
            <div id="current_user_id">
              <%= current_user.id %>
            </div>
          </div>
            <% if current_user.total_unread_messages_nbr %>
                <div class="badge badge-blue <%= 'hidden' if current_user.total_unread_messages_nbr == 0 %>" id="notification-<%= current_user.id %>">
                  <%= current_user.total_unread_messages_nbr %>
                </div>
            <% end %>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "elements/man.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to current_user do %>
                <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                <%= t(".profile", default: "Edit Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->


  <div class="navbar-wagon-item hidden-md hidden-lg" id="navbar-smartphone">

    <% if user_signed_in? %>

      <%= link_to channel_path(Channel.first), class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <%= image_tag 'elements/Courrier-01.png', alt: 'menu-item', class: "courrier" %>
          <!-- <div class="badge badge-blue">3</div> -->
        </div>
      <% end %>
      <div class="dropdown">
        <%= image_tag 'elements/Menu-01.png', alt: 'dropdown', id:'dropdown-bars', class: 'dropdown-toggle', data: {toggle: 'dropdown'} %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to current_user do %>
              <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to edit_user_registration_path do %>
              <%= t(".profile", default: "Edit Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
      <% else %>

        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <% end %>
  </div>
</div>