config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, only: [:index , :show]
  scope "(:locale)", locale: /fr|en/ do
    get 'birthday', to: "pages#birthday", as: "birthday"
    get 'selection', to: "pages#selection", as: "selection"

    root to: "users#index", constraints: lambda { |r| r.env["warden"].authenticate? }
    root to: 'pages#home'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :channels, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :subscriptions, only: [:create, :destroy]
    resources :messages, only: [:create, :destroy]
  end

  get 'first-connection', to: "channels#first_connection"
  delete 'delete-selected-user/:id', to: "channels#delete_selected_user", as: "delete_selected_user"

  mount ActionCable.server => '/cable'
  mount Attachinary::Engine => "/attachinary"

  patch 'picture/:id', to: "users#picture", as: "picture"
  put 'picture/:id', to: "users#picture"

end

app/views/pages/home.html.erb
<div id="pages-home">
  <div class="birthday-select">
    <h1>Twweams nés depuis le chargement de la page </h1>
    <div id="nbr-twweams"></div>

    <div class="form-container">
      <h2> Enter your birthday </h2>
      <div class="form">
        <%= simple_form_for :birthday, url: birthday_path, class: 'birthday-form',method: :get do |f| %>
            <%= f.input :birthdate, as: :date, start_year: Date.today.year - 110, end_year: Date.today.year, label: false %>
          <%= f.button :submit, 'Go !', id:"go-btn" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="fb-share-button" data-href="http://www.twweams.com" data-layout="button_count" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.twweams.com%2F&amp;src=sdkpreparse">Partager</a></div>
  <a class="twitter-share-button" href="https://twitter.com/intent/tweet?text=Twweams est la ! " data-size="large">Tweet</a>



  <div class="text-center margin-bottom-lg">
    <h2>Comment ca marche ?</h2>
    <div class="hidden-md hidden-lg">
      <iframe src="https://player.vimeo.com/video/241765313" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    </div>
    <div class="hidden-xs hidden-sm">
      <iframe src="https://player.vimeo.com/video/241765313" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    </div>
  </div>

  <div id="fb-root"></div>
</div>

<%= javascript_include_tag 'counter-home' %>